package TM;

import java.awt.*;
import javax.swing.JOptionPane;

public class AdminFront extends javax.swing.JFrame {
        
    Image image = Toolkit.getDefaultToolkit().getImage("Universe.png");
    JDBC data = new JDBC();
    
    /**
     * Creates new form AdminFront
     */
    public AdminFront() {
        initComponents();
        setTitle("Universe Tutorial Manager");
        labelID.setVisible(false);
        formattedTextField.setVisible(false);
        buttonRemove.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSide = new javax.swing.JPanel();
        labelOrganisation = new javax.swing.JLabel();
        labelTeacher = new javax.swing.JLabel();
        labelFeedback = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        labelID = new javax.swing.JLabel();
        formattedTextField = new javax.swing.JFormattedTextField();
        buttonRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(image);

        panelSide.setBackground(new java.awt.Color(153, 0, 255));
        panelSide.setFocusable(false);

        labelOrganisation.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelOrganisation.setText("Organisations");
        labelOrganisation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOrganisationMouseClicked(evt);
            }
        });

        labelTeacher.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTeacher.setText("Teachers");
        labelTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTeacherMouseClicked(evt);
            }
        });

        labelFeedback.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelFeedback.setText("Feedbacks");
        labelFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFeedbackMouseClicked(evt);
            }
        });

        buttonBack.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        buttonBack.setText("BACK");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSideLayout = new javax.swing.GroupLayout(panelSide);
        panelSide.setLayout(panelSideLayout);
        panelSideLayout.setHorizontalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTeacher)
                    .addComponent(labelOrganisation)
                    .addGroup(panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonBack)
                        .addComponent(labelFeedback)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelSideLayout.setVerticalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(labelOrganisation)
                .addGap(36, 36, 36)
                .addComponent(labelTeacher)
                .addGap(41, 41, 41)
                .addComponent(labelFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addGap(50, 50, 50))
        );

        table.setBackground(new java.awt.Color(204, 204, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setColumnSelectionAllowed(true);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        labelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelID.setText("ID:");

        buttonRemove.setBackground(new java.awt.Color(153, 102, 255));
        buttonRemove.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(labelID)
                        .addGap(37, 37, 37)
                        .addComponent(formattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(buttonRemove)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(formattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRemove))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelOrganisationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOrganisationMouseClicked
        table = data.view(table, "org");
    }//GEN-LAST:event_labelOrganisationMouseClicked

    private void labelTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTeacherMouseClicked
        labelID.setVisible(true);
        formattedTextField.setVisible(true);
        buttonRemove.setVisible(true);
        table = data.view(table, "tutor");
    }//GEN-LAST:event_labelTeacherMouseClicked

    private void labelFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFeedbackMouseClicked
        table = data.view(table, "feedbacks");
    }//GEN-LAST:event_labelFeedbackMouseClicked

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        String id = formattedTextField.getText();
        if(!id.equals(""))
            table = data.removeTutor(table, id);
        else
            JOptionPane.showMessageDialog(this, "No ID has been entered!", "Message", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JFormattedTextField formattedTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFeedback;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelOrganisation;
    private javax.swing.JLabel labelTeacher;
    private javax.swing.JPanel panelSide;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}