package TM;

import java.awt.*;

public class StudentFront extends javax.swing.JFrame {

        Image image = Toolkit.getDefaultToolkit().getImage("Universe.png");
    /**
     * Creates new form StudentFront
     */
    public StudentFront() {
        initComponents();
        setTitle("Universe Tutorial Manager");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSide = new javax.swing.JPanel();
        buttonBack = new javax.swing.JButton();
        panelSide1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonGet = new javax.swing.JButton();
        buttonGetAttend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDetail = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(image);

        panelSide.setBackground(new java.awt.Color(153, 0, 255));
        panelSide.setFocusable(false);

        buttonBack.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        buttonBack.setText("BACK");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSideLayout = new javax.swing.GroupLayout(panelSide);
        panelSide.setLayout(panelSideLayout);
        panelSideLayout.setHorizontalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(buttonBack)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelSideLayout.setVerticalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(buttonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSide1.setBackground(new java.awt.Color(153, 0, 255));
        panelSide1.setFocusable(false);

        javax.swing.GroupLayout panelSide1Layout = new javax.swing.GroupLayout(panelSide1);
        panelSide1.setLayout(panelSide1Layout);
        panelSide1Layout.setHorizontalGroup(
            panelSide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        panelSide1Layout.setVerticalGroup(
            panelSide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        buttonGet.setBackground(new java.awt.Color(153, 102, 255));
        buttonGet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonGet.setText("Get Messages");
        buttonGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetActionPerformed(evt);
            }
        });

        buttonGetAttend.setBackground(new java.awt.Color(153, 102, 255));
        buttonGetAttend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonGetAttend.setText("Get Attendance");
        buttonGetAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetAttendActionPerformed(evt);
            }
        });

        textAreaDetail.setEditable(false);
        textAreaDetail.setColumns(20);
        textAreaDetail.setRows(5);
        jScrollPane1.setViewportView(textAreaDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(buttonGetAttend)
                                .addGap(65, 65, 65)
                                .addComponent(buttonGet))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(panelSide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGet)
                    .addComponent(buttonGetAttend))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetActionPerformed
        String text = new JDBC().viewDetail(ID);
        textAreaDetail.setText(text);
        table = new JDBC().viewMessage(table,ID);
    }//GEN-LAST:event_buttonGetActionPerformed

    private void buttonGetAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetAttendActionPerformed
        String text = new JDBC().viewDetail(ID);
        textAreaDetail.setText(text);
        table = new JDBC().viewAttend(table, ID);
    }//GEN-LAST:event_buttonGetAttendActionPerformed
    
    int ID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonGet;
    private javax.swing.JButton buttonGetAttend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelSide;
    private javax.swing.JPanel panelSide1;
    private javax.swing.JTable table;
    private javax.swing.JTextArea textAreaDetail;
    // End of variables declaration//GEN-END:variables
}