package TM;

import java.awt.*;
import javax.swing.*;
import java.util.*;


public class TutorFront extends JFrame {

    Image image = Toolkit.getDefaultToolkit().getImage("Universe.png");
    JDBC data = new JDBC();
    Tutor tutor = new Tutor();
    Student student = new Student();
    String organisation, username;
    
    /**
     * Creates new form TutorFront
     */
    public TutorFront() {
        initComponents();
        setTitle("Universe Tutorial Manager");
        tutor.organisation = organisation;
        tutor.username = username;
        labelDisplay.setVisible(false);
        labelFeedbackStatus.setVisible(false);
    }                              
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        panelSide = new javax.swing.JPanel();
        buttonBack = new javax.swing.JButton();
        tabAccount = new javax.swing.JTabbedPane();
        panelStudents = new javax.swing.JPanel();
        labName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        labClass = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        labFees = new javax.swing.JLabel();
        spinnerClass = new javax.swing.JSpinner();
        spinnerDate = new javax.swing.JSpinner();
        spinnerFee = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelDetails = new javax.swing.JLabel();
        labID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        panelAttendance = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAttendance = new javax.swing.JTable();
        toggleButtonPresent = new javax.swing.JToggleButton();
        labelID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        labelClass = new javax.swing.JLabel();
        labelPresence = new javax.swing.JLabel();
        spinnerStandard = new javax.swing.JSpinner();
        labelDate = new javax.swing.JLabel();
        spinnerToday = new javax.swing.JSpinner();
        buttonView = new javax.swing.JButton();
        buttonAllPresent = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panelMessage = new javax.swing.JPanel();
        labelMessage = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        labelDisplay = new javax.swing.JLabel();
        buttonSend = new javax.swing.JToggleButton();
        labelClassToSend = new javax.swing.JLabel();
        comboBoxClass = new javax.swing.JComboBox<>();
        labelTip = new javax.swing.JLabel();
        panelPayments = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePay = new javax.swing.JTable();
        labelClient = new javax.swing.JLabel();
        textClient = new javax.swing.JTextField();
        labelClass2 = new javax.swing.JLabel();
        labelDue = new javax.swing.JLabel();
        labelPaid = new javax.swing.JLabel();
        toggleButtonPaid = new javax.swing.JToggleButton();
        spinnerDue = new javax.swing.JSpinner();
        spinnerClassPay = new javax.swing.JSpinner();
        labelTotal = new javax.swing.JLabel();
        labelUnpaid = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        spinnerYear = new javax.swing.JSpinner();
        labelSubTotal = new javax.swing.JLabel();
        buttonShowPay = new javax.swing.JButton();
        panelFeedback = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        feedbackTextArea = new javax.swing.JTextArea();
        labelFeedback = new javax.swing.JLabel();
        labelFeedbackStatus = new javax.swing.JLabel();
        buttonFeed = new javax.swing.JButton();
        panelAccount = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        buttonAccount = new javax.swing.JButton();
        labelUserOld = new javax.swing.JLabel();
        txtUserOld = new javax.swing.JTextField();
        buttonDeleteAccount = new javax.swing.JButton();
        buttonClearAll = new javax.swing.JButton();
        labelWarning = new javax.swing.JLabel();

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(image);

        panelSide.setBackground(new java.awt.Color(153, 0, 255));
        panelSide.setFocusable(false);

        buttonBack.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buttonBack.setText("<< LOG OUT");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSideLayout = new javax.swing.GroupLayout(panelSide);
        panelSide.setLayout(panelSideLayout);
        panelSideLayout.setHorizontalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addGap(16, 16, 16))
        );
        panelSideLayout.setVerticalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAccount.setBackground(new java.awt.Color(153, 102, 255));
        tabAccount.setToolTipText("Select the features to explore more.");
        tabAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        labName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labName.setText("Name");

        labPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labPhone.setText("Phone");

        labClass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labClass.setText("Class");

        labDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labDate.setText("Date of Joining");

        labFees.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labFees.setText("Fees (per month)");

        spinnerClass.setModel(new javax.swing.SpinnerNumberModel(10, 1, 12, 1));

        spinnerDate.setModel(new javax.swing.SpinnerDateModel());
        spinnerDate.setToolTipText(" Month /Day /Year ");

        spinnerFee.setModel(new javax.swing.SpinnerNumberModel(600, 250, null, 100));

        tableStudent.setBackground(new java.awt.Color(204, 204, 255));
        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Student", "Class", "Mobile", "Date joined", "Fees"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStudent.setColumnSelectionAllowed(true);
        tableStudent.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tableStudent.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableStudent);
        tableStudent.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        buttonAdd.setBackground(new java.awt.Color(153, 102, 255));
        buttonAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAdd.setText("ADD");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonUpdate.setBackground(new java.awt.Color(153, 102, 255));
        buttonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonUpdate.setText("UPDATE");
        buttonUpdate.setToolTipText("Enter the correct details of name,phone,class,date joined and fees.");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(153, 102, 255));
        buttonDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDelete.setText("DELETE");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonClear.setBackground(new java.awt.Color(153, 102, 255));
        buttonClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonClear.setText("CLEAR");
        buttonClear.setToolTipText("Clears only the typed data.");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        labelDetails.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelDetails.setText("Student Details :");

        labID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labID.setText("ID");

        txtID.setToolTipText("Enter the ID of the student to be updated/deleted");

        javax.swing.GroupLayout panelStudentsLayout = new javax.swing.GroupLayout(panelStudents);
        panelStudents.setLayout(panelStudentsLayout);
        panelStudentsLayout.setHorizontalGroup(
            panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentsLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentsLayout.createSequentialGroup()
                        .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelStudentsLayout.createSequentialGroup()
                                .addComponent(labFees, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerFee, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelStudentsLayout.createSequentialGroup()
                                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labClass, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(114, 114, 114))
                    .addGroup(panelStudentsLayout.createSequentialGroup()
                        .addComponent(labDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonClear)
                    .addComponent(buttonAdd)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelStudentsLayout.createSequentialGroup()
                        .addComponent(buttonUpdate)
                        .addGap(27, 27, 27)
                        .addComponent(buttonDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelStudentsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDetails))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        panelStudentsLayout.setVerticalGroup(
            panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentsLayout.createSequentialGroup()
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentsLayout.createSequentialGroup()
                        .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelStudentsLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labName))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labPhone)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labClass)
                            .addComponent(spinnerClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labDate)
                            .addComponent(spinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labID))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentsLayout.createSequentialGroup()
                        .addComponent(buttonAdd)
                        .addGap(90, 90, 90)))
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFees)
                    .addComponent(spinnerFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(labelDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        tabAccount.addTab("STUDENTS", panelStudents);

        tableAttendance.setBackground(new java.awt.Color(204, 204, 255));
        tableAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Class", "Present"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAttendance.setColumnSelectionAllowed(true);
        tableAttendance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableAttendance.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableAttendance);
        tableAttendance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableAttendance.getColumnModel().getColumnCount() > 0) {
            tableAttendance.getColumnModel().getColumn(0).setResizable(false);
            tableAttendance.getColumnModel().getColumn(1).setResizable(false);
            tableAttendance.getColumnModel().getColumn(2).setResizable(false);
            tableAttendance.getColumnModel().getColumn(3).setResizable(false);
        }

        toggleButtonPresent.setBackground(new java.awt.Color(153, 102, 255));
        toggleButtonPresent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toggleButtonPresent.setText("Present");
        toggleButtonPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonPresentActionPerformed(evt);
            }
        });

        labelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelID.setText("ID");

        labelClass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelClass.setText("Class");

        labelPresence.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPresence.setText("Presence");

        spinnerStandard.setModel(new javax.swing.SpinnerNumberModel(10, 1, 12, 1));

        labelDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDate.setText("Date");

        spinnerToday.setModel(new javax.swing.SpinnerDateModel());
        spinnerToday.setToolTipText(" Month /Day /Year");

        buttonView.setBackground(new java.awt.Color(153, 102, 255));
        buttonView.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonView.setText("VIEW");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        buttonAllPresent.setBackground(new java.awt.Color(153, 102, 255));
        buttonAllPresent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAllPresent.setText("MAKE ALL PRESENT");
        buttonAllPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllPresentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAttendanceLayout = new javax.swing.GroupLayout(panelAttendance);
        panelAttendance.setLayout(panelAttendanceLayout);
        panelAttendanceLayout.setHorizontalGroup(
            panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAttendanceLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAttendanceLayout.createSequentialGroup()
                        .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelClass, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelAttendanceLayout.createSequentialGroup()
                                .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelPresence)
                                    .addComponent(labelID))
                                .addGap(39, 39, 39)
                                .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(toggleButtonPresent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textID))
                                .addGap(63, 63, 63))
                            .addGroup(panelAttendanceLayout.createSequentialGroup()
                                .addComponent(buttonView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonAllPresent)
                                .addGap(28, 28, 28)))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        panelAttendanceLayout.setVerticalGroup(
            panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAttendanceLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDate)
                    .addComponent(spinnerToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelID))
                .addGap(25, 25, 25)
                .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClass)
                    .addComponent(spinnerStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleButtonPresent)
                    .addComponent(labelPresence))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonView, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAllPresent, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        tabAccount.addTab("ATTENDANCE", panelAttendance);

        labelMessage.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labelMessage.setText("Type a message");

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane4.setViewportView(messageTextArea);

        labelDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDisplay.setForeground(new java.awt.Color(255, 51, 51));
        labelDisplay.setText("Status will be displayed here.");

        buttonSend.setBackground(new java.awt.Color(153, 102, 255));
        buttonSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSend.setText("SEND ");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });

        labelClassToSend.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labelClassToSend.setText("Select the class");

        comboBoxClass.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        comboBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboBoxClass.setSelectedIndex(8);
        comboBoxClass.setSelectedItem(9);

        labelTip.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTip.setForeground(new java.awt.Color(153, 51, 255));
        labelTip.setText("TIP: Next time you want to send the same message to a different class, just select the class and Send.");

        javax.swing.GroupLayout panelMessageLayout = new javax.swing.GroupLayout(panelMessage);
        panelMessage.setLayout(panelMessageLayout);
        panelMessageLayout.setHorizontalGroup(
            panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMessageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMessageLayout.createSequentialGroup()
                        .addComponent(buttonSend)
                        .addGap(311, 311, 311))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMessageLayout.createSequentialGroup()
                        .addComponent(labelDisplay)
                        .addGap(245, 245, 245))))
            .addGroup(panelMessageLayout.createSequentialGroup()
                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMessageLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(panelMessageLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMessage)
                                    .addComponent(labelClassToSend, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelMessageLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(labelTip)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelMessageLayout.setVerticalGroup(
            panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMessageLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClassToSend)
                    .addComponent(comboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMessage))
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(labelDisplay)
                .addGap(46, 46, 46)
                .addComponent(buttonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(labelTip)
                .addGap(24, 24, 24))
        );

        tabAccount.addTab("MESSAGE", panelMessage);

        tablePay.setBackground(new java.awt.Color(204, 204, 255));
        tablePay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Date", "Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePay.setColumnSelectionAllowed(true);
        tablePay.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tablePay.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablePay);
        tablePay.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablePay.getColumnModel().getColumnCount() > 0) {
            tablePay.getColumnModel().getColumn(0).setResizable(false);
            tablePay.getColumnModel().getColumn(3).setResizable(false);
        }

        labelClient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelClient.setText("ID");

        labelClass2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelClass2.setText("Class");

        labelDue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDue.setText("Due date");

        labelPaid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPaid.setText("Status");

        toggleButtonPaid.setBackground(new java.awt.Color(153, 102, 255));
        toggleButtonPaid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toggleButtonPaid.setText("Not Paid");
        toggleButtonPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonPaidActionPerformed(evt);
            }
        });

        spinnerDue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spinnerDue.setModel(new javax.swing.SpinnerListModel(new String[] {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"}));
        spinnerDue.setToolTipText("Month");

        spinnerClassPay.setModel(new javax.swing.SpinnerNumberModel(10, 1, 12, 1));
        spinnerClassPay.setName(""); // NOI18N
        spinnerClassPay.setOpaque(true);

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 51, 51));
        labelTotal.setText("TOTAL RECEIVED : ");

        labelUnpaid.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelUnpaid.setText("Unpaid Students :");

        spinnerYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spinnerYear.setModel(new javax.swing.SpinnerNumberModel(2023, 1900, 2500, 1));
        spinnerYear.setToolTipText("Year ");

        labelSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSubTotal.setForeground(new java.awt.Color(255, 51, 51));
        labelSubTotal.setText("SUBTOTAL : ");

        buttonShowPay.setBackground(new java.awt.Color(153, 102, 255));
        buttonShowPay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonShowPay.setText("SHOW");
        buttonShowPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPaymentsLayout = new javax.swing.GroupLayout(panelPayments);
        panelPayments.setLayout(panelPaymentsLayout);
        panelPaymentsLayout.setHorizontalGroup(
            panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaymentsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonShowPay)
                .addGap(174, 174, 174))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaymentsLayout.createSequentialGroup()
                .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPaymentsLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPaymentsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane3))
                            .addComponent(labelUnpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPaymentsLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toggleButtonPaid, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(textClient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaymentsLayout.createSequentialGroup()
                                .addComponent(labelDue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaymentsLayout.createSequentialGroup()
                                .addComponent(labelClass2)
                                .addGap(40, 40, 40)))
                        .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPaymentsLayout.createSequentialGroup()
                                .addComponent(spinnerDue, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinnerClassPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPaymentsLayout.createSequentialGroup()
                        .addContainerGap(512, Short.MAX_VALUE)
                        .addComponent(labelSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPaymentsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(115, 115, 115))
        );
        panelPaymentsLayout.setVerticalGroup(
            panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaymentsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClient)
                    .addComponent(spinnerClassPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClass2))
                .addGap(27, 27, 27)
                .addGroup(panelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDue)
                    .addComponent(spinnerDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleButtonPaid)
                    .addComponent(labelPaid))
                .addGap(18, 18, 18)
                .addComponent(buttonShowPay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUnpaid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSubTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        tabAccount.addTab("PAYMENTS", panelPayments);

        feedbackTextArea.setColumns(20);
        feedbackTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        feedbackTextArea.setRows(5);
        jScrollPane5.setViewportView(feedbackTextArea);

        labelFeedback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFeedback.setText("Enter your feedback/queries :");

        labelFeedbackStatus.setText("Status will be displayed here.");

        buttonFeed.setBackground(new java.awt.Color(153, 102, 255));
        buttonFeed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonFeed.setText("SEND");
        buttonFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFeedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFeedbackLayout = new javax.swing.GroupLayout(panelFeedback);
        panelFeedback.setLayout(panelFeedbackLayout);
        panelFeedbackLayout.setHorizontalGroup(
            panelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeedbackLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(labelFeedback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFeedbackLayout.createSequentialGroup()
                .addGap(0, 193, Short.MAX_VALUE)
                .addGroup(panelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFeedbackLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFeedbackLayout.createSequentialGroup()
                        .addComponent(buttonFeed)
                        .addGap(352, 352, 352))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFeedbackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelFeedbackStatus)
                .addGap(312, 312, 312))
        );
        panelFeedbackLayout.setVerticalGroup(
            panelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeedbackLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(labelFeedback)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(buttonFeed)
                .addGap(67, 67, 67)
                .addComponent(labelFeedbackStatus)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        tabAccount.addTab("FEEDBACK", panelFeedback);

        txtUser.setToolTipText("Enter the new username which you want to use henceforth.");

        labelUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUser.setText("New Username");

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPassword.setText("New Password");

        buttonAccount.setBackground(new java.awt.Color(153, 102, 255));
        buttonAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAccount.setText("UPDATE");
        buttonAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccountActionPerformed(evt);
            }
        });

        labelUserOld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUserOld.setText("Current Username");

        txtUserOld.setToolTipText("Enter the current username which you want to change.");

        buttonDeleteAccount.setBackground(new java.awt.Color(153, 102, 255));
        buttonDeleteAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDeleteAccount.setText("DELETE ACCOUNT");
        buttonDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAccountActionPerformed(evt);
            }
        });

        buttonClearAll.setBackground(new java.awt.Color(153, 102, 255));
        buttonClearAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonClearAll.setText("CLEAR ALL STUDENT RECORDS");
        buttonClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearAllActionPerformed(evt);
            }
        });

        labelWarning.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        labelWarning.setForeground(new java.awt.Color(255, 0, 51));
        labelWarning.setText("NOTE: Think twice before you do.");

        javax.swing.GroupLayout panelAccountLayout = new javax.swing.GroupLayout(panelAccount);
        panelAccount.setLayout(panelAccountLayout);
        panelAccountLayout.setHorizontalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUser)
                            .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUserOld, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserOld, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAccountLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(buttonAccount))))
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addComponent(buttonClearAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(buttonDeleteAccount)))
                .addGap(195, 195, 195))
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelWarning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAccountLayout.setVerticalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserOld)
                    .addComponent(txtUserOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUser))
                .addGap(29, 29, 29)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(buttonAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(labelWarning)
                .addGap(45, 45, 45))
        );

        tabAccount.addTab("ACCOUNT", panelAccount);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAccount))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabAccount)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleButtonPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonPresentActionPerformed
        if(textID.getText().isEmpty())
            new NoIdException();
        else {
            if(toggleButtonPresent.isSelected()) {
                toggleButtonPresent.setText("Absent");
                student.present=false;
            }
            else {
                toggleButtonPresent.setText("Present");
                student.present=true;
            }
            getDetailsForAttend();
            data.updatePresence(student);
            buttonViewActionPerformed(evt); // getting table
        }
    }//GEN-LAST:event_toggleButtonPresentActionPerformed

    private void buttonAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccountActionPerformed
        data.updateTutor(txtUserOld.getText(), txtUser.getText(), txtPassword.getText());
    }//GEN-LAST:event_buttonAccountActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        getDetailsForModify();
        if(student.name.isEmpty())
            User.interrupt("Enter the student's name.");
        else if( !student.phone.isEmpty() && new User().isValidPhone(student.phone) == false)
            User.interrupt( "Invalid mobile number");
        else
            data.addStudent(student);
        viewStudents(); // getting table
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        if(txtID.getText().isEmpty())
            new NoIdException();
        else {
            getDetailsForModify();
            if(student.name.isEmpty())
                User.interrupt( "Enter the student's name.");
            else
                data.updateStudent(student);
        }
        viewStudents(); // getting table
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        if(txtID.getText().isEmpty())
            new NoIdException();
        else {
            getDetailsForModify();
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove "+student.name+"?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if( JOptionPane.YES_OPTION == result) {
                data.deleteStudent(student);
                viewStudents(); // getting table
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void toggleButtonPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonPaidActionPerformed
        if(textClient.getText().isEmpty())
            new NoIdException(); 
        else {
            if(toggleButtonPaid.isSelected()) {
                student.paid=true;
                toggleButtonPaid.setText("Paid");
            }
            else {
                student.paid=false;
                toggleButtonPaid.setText("Not Paid");
            }
            getDetailsForPay();
            data.updatePay(student);
            buttonShowPayActionPerformed(evt); // getting table
            labelSubTotal.setText("SUBTOTAL: "+data.getSubTotal(student) );
            labelTotal.setText("TOTAL RECEIVED: "+ data.getTotal(student) );
        }
    }//GEN-LAST:event_toggleButtonPaidActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        txtName.setText("");
        txtPhone.setText("");
        spinnerClass.setValue(10);
        spinnerDate.setValue(new Date());
        spinnerFee.setValue(600);
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        getDetailsForAttend();
        tableAttendance = data.showAttend(student);
    }//GEN-LAST:event_buttonViewActionPerformed

    private void buttonAllPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllPresentActionPerformed
        getDetailsForAttend();
        data.makeAllPresent(student);
        buttonViewActionPerformed(evt); // getting table
    }//GEN-LAST:event_buttonAllPresentActionPerformed

    private void buttonDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAccountActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if( JOptionPane.YES_OPTION == result) 
            data.deleteAccount(txtUserOld.getText());
    }//GEN-LAST:event_buttonDeleteAccountActionPerformed

    private void buttonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearAllActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete? \n NOTE: The records cannot be retrieved.", "Confirmation", JOptionPane.YES_NO_OPTION);
        if( JOptionPane.YES_OPTION == result) 
            data.deleteAll(organisation);
    }//GEN-LAST:event_buttonClearAllActionPerformed

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        int std = Integer.parseInt( comboBoxClass.getSelectedItem().toString() );
        String info = messageTextArea.getText();
        if(info.isEmpty())
            JOptionPane.showMessageDialog(this,"We cannot find any message to be sent!","Message",JOptionPane.UNDEFINED_CONDITION);
        else if(data.message(organisation, username, info, std))
            labelDisplay.setText("Message has been sent.");
        else
            labelDisplay.setText("Oops! Sorry, your message could not be sent.");
        labelDisplay.setVisible(true);
    }//GEN-LAST:event_buttonSendActionPerformed

    private void buttonFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFeedActionPerformed
        String feedback = feedbackTextArea.getText();
        if(feedback.isEmpty())
            JOptionPane.showMessageDialog(this,"We cannot find any message to be sent!","Message",JOptionPane.UNDEFINED_CONDITION);
        else if( data.feed(username, feedback) )
            labelFeedbackStatus.setText("Your feedback has been sent!");
        else
            labelFeedbackStatus.setText("Oops! Sorry, your message could not be sent.");
        labelFeedbackStatus.setVisible(true);
    }//GEN-LAST:event_buttonFeedActionPerformed

    private void buttonShowPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowPayActionPerformed
        getDetailsForPay();
        tablePay = data.showPay(student);
    }//GEN-LAST:event_buttonShowPayActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccount;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonAllPresent;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonClearAll;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDeleteAccount;
    private javax.swing.JButton buttonFeed;
    private javax.swing.JToggleButton buttonSend;
    private javax.swing.JButton buttonShowPay;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton buttonView;
    private javax.swing.JComboBox<String> comboBoxClass;
    private javax.swing.JTextArea feedbackTextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labClass;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labFees;
    private javax.swing.JLabel labID;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labPhone;
    private javax.swing.JLabel labelClass;
    private javax.swing.JLabel labelClass2;
    private javax.swing.JLabel labelClassToSend;
    private javax.swing.JLabel labelClient;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDetails;
    private javax.swing.JLabel labelDisplay;
    private javax.swing.JLabel labelDue;
    private javax.swing.JLabel labelFeedback;
    private javax.swing.JLabel labelFeedbackStatus;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelPaid;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPresence;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTip;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelUnpaid;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUserOld;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JPanel panelAccount;
    private javax.swing.JPanel panelAttendance;
    private javax.swing.JPanel panelFeedback;
    private javax.swing.JPanel panelMessage;
    private javax.swing.JPanel panelPayments;
    private javax.swing.JPanel panelSide;
    private javax.swing.JPanel panelStudents;
    private javax.swing.JSpinner spinnerClass;
    private javax.swing.JSpinner spinnerClassPay;
    private javax.swing.JSpinner spinnerDate;
    private javax.swing.JSpinner spinnerDue;
    private javax.swing.JSpinner spinnerFee;
    private javax.swing.JSpinner spinnerStandard;
    private javax.swing.JSpinner spinnerToday;
    private javax.swing.JSpinner spinnerYear;
    private javax.swing.JTabbedPane tabAccount;
    private javax.swing.JTable tableAttendance;
    private javax.swing.JTable tablePay;
    private javax.swing.JTable tableStudent;
    private javax.swing.JTextField textClient;
    private javax.swing.JTextField textID;
    private javax.swing.JToggleButton toggleButtonPaid;
    private javax.swing.JToggleButton toggleButtonPresent;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserOld;
    // End of variables declaration//GEN-END:variables

private void viewStudents() {
    tableStudent = data.showStudent(organisation);
}
    
private void getDetailsForModify() {
    student.ID = Integer.parseInt(txtID.getText());
    student.name = txtName.getText();
    student.phone = txtPhone.getText();
    student.standard = (int) spinnerClass.getValue();
    student.date = (Date) spinnerDate.getValue();
    student.fee = (int) spinnerFee.getValue();
}

private void getDetailsForAttend() {
    student.ID = Integer.parseInt(textID.getText());
    student.standard = (int) spinnerStandard.getValue();
    student.date = (Date) spinnerToday.getValue();
    student.dateLong = student.date.getTime();  // getTime() returns a long which is used by sql.Date
}

private void getDetailsForPay() {
    student.ID = Integer.parseInt(textClient.getText());
    student.standard = (int) spinnerClassPay.getValue();
    String month = spinnerDue.getValue().toString();
    String year = spinnerYear.getValue().toString();
    student.month = month+","+year;
}

}